name: flutter_ble_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_blue_plus: ^1.34.5
  get: ^4.6.6
  permission_handler: ^11.3.1
  flutter_reactive_ble: ^5.0.0
  animated_text_kit: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.10.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/playstore.png"

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/background.png
    - assets/backgroundlist.png
    - assets/background2.png
    

# Fonts section if needed in the future:
# fonts:
#   - family: CustomFont
#     fonts:
#       - asset: fonts/CustomFont-Regular.ttf
